#!/bin/bash

BASE="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

PREFS_DIR="$HOME/Library/Preferences/Aquamacs Emacs"
SUPPORT_DIR="$HOME/Library/Application Support/Aquamacs Emacs"
OLD=hub.old

[[ -d $PREFS_DIR ]] || mkdir -p "$PREFS_DIR"
[[ -d $SUPPORT_DIR ]] || mkdir -p "$SUPPORT_DIR"
[[ -d $HOME/.emacs.d ]] || mkdir -p "$HOME/.emacs.d"


function replace-pref-file {
  PREF_PATH=$PREFS_DIR/$1
  if [[ -e $PREF_PATH && ! -L $PREF_PATH ]]; then
    mv -f "$PREF_PATH" "$PREF_PATH.$OLD"
  fi
  ln -fs "$BASE/$2" "$PREF_PATH"
}

function replace-support-file {
  SUPPORT_FILE=$SUPPORT_DIR/$1
  if [[ -e $SUPPORT_FILE && ! -L $SUPPORT_FILE ]]; then
    mv -f "$SUPPORT_FILE" "$SUPPORT_FILE.$OLD"
  fi
  rm -f "$SUPPORT_FILE"
  ln -s "$BASE/$2" "$SUPPORT_FILE"
}

replace-pref-file Preferences.el preferences.el
replace-support-file elpa bundle

ln -s "$BASE/bundle" "$HOME/.emacs.d/bundle"

git submodule update --init --quiet

