#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

PREFS_DIR="$HOME/Library/Preferences/Aquamacs Emacs"
SUPPORT_DIR="$HOME/Library/Application Support/Aquamacs Emacs"
OLD=hub.old

function replace-pref-file {
  PREF_PATH=$PREFS_DIR/$1
  if [[ -e $PREF_PATH && ! -L $PREF_PATH ]]; then
    mv -f "$PREF_PATH" "$PREF_PATH.$OLD"
  fi
  ln -fs "$SCRIPT_DIR/$2" "$PREF_PATH"
}

function replace-support-file {
  SUPPORT_PATH=$SUPPORT_DIR/$1
  if [[ -e $SUPPORT_PATH && ! -L $SUPPORT_PATH ]]; then
    mv -f "$SUPPORT_PATH" "$SUPPORT_PATH.$OLD"
  fi
  ln -fs "$SCRIPT_DIR/$2" "$SUPPORT_PATH"
}


replace-pref-file Preferences.el preferences.el
replace-support-file elpa elpa

git submodule update --init --quiet

