#!/bin/bash

if [[ $# -eq 0 ]]; then 
  echo "Usage: $0 <package-name>"
  exit 1
fi

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PACKAGE_NAME=$(basename $1)
PACKAGE_DST=$SCRIPT_DIR/elpa/$PACKAGE_NAME
if [[ -e $PACKAGE_DST ]]; then
  read -e -p "Add locally found $PACKAGE_NAME? " YN
  if [[ $YN = "y" || $YN = "Y" ]]; then
    git add $PACKAGE_DST
    git commit --quiet -m "Add $PACKAGE_NAME"
  fi
fi

