#!/bin/bash

if [[ $# -eq 0 ]]; then 
  echo "Usage: $0 <package-name>"
  exit 1
fi

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PACKAGE_NAME=$(basename $1)
PACKAGE_DST=$SCRIPT_DIR/elpa/$PACKAGE_NAME

if [[ -e $PACKAGE_DST ]]; then
  git rm -r "$PACKAGE_DST"
  git commit -m "Remove $PACKAGE_NAME"
fi

